#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

    FROM 2109199812/docker-latex


    ENV DEBIAN_FRONTEND=dialog \
        LANG=C.UTF-8 \
        LC_ALL=C.UTF-8